[package]
name = "gatekeeper"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
tokio = { version = "1.0", features = ["full"] }
axum = "0.8.9"
redis = { version = "1.2.1", features = ["tokio-comp"] }
deadpool-redis = "0.23.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
