use bevy::math::{Rect, Vec2};
use serde::{Deserialize, Serialize};

// ==========================================
// 1. DATA STRUCTURES
// ==========================================

/// Sent by clients via the Gatekeeper -> Broker -> SpatialServer
/// to update their geographical position in the world.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PositionUpdate {
    pub client_id: u32,
    pub x: f32,
    pub y: f32,
}

/// The actionable decisions generated by the SpatialService.
/// These are translated into binary UDP packets and sent out to Broker/Orchestrator.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum SpatialAction {
    // Tell the Broker to start sending Ghost data to this client
    Subscribe { client_id: u32, topic: [u8; 32] },
    // Tell the Broker to stop sending Ghost data to save bandwidth
    Unsubscribe { client_id: u32, topic: [u8; 32] },
    // Tell the client which nearby shards exist (used for client-side interpolation/UI)
    CrossingAlert { client_id: u32, shards: Vec<u32> },
    // Tell the client to change its primary Authority target
    AuthorityChange { client_id: u32, old_shard: u32, new_shard: u32 },
    // Tell the Orchestrator to boot 4 new servers to split a crowded shard
    ScaleUp { parent_shard: u32, new_shards: Vec<u32> },
    // Tell the Orchestrator to shut down 4 empty child servers and merge back to parent
    ScaleDown { parent_shard: u32, old_shards: Vec<u32> },
}

/// Helper to convert a simple string into a fixed 32-byte array (used for PubSub topics)
pub fn string_to_topic(s: &str) -> [u8; 32] {
    let mut topic = [0u8; 32];
    let bytes = s.as_bytes();
    let len = bytes.len().min(32);
    topic[..len].copy_from_slice(&bytes[..len]);
    topic
}

// ==========================================
// 2. THE QUADTREE STRUCTURE
// ==========================================

/// The QuadTree represents the geographical partitioning of the game map.
/// It recursively divides 2D space into 4 quadrants.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuadTree {
    pub bounds: Rect,                          // The 2D geographical area this node covers
    pub depth: u8,                             // How deep we are in the tree
    pub max_depth: u8,                         // The maximum allowed subdivisions
    pub children: Option<Box<[QuadTree; 4]>>,  // The 4 child nodes (NW, NE, SW, SE)
    pub shard_id: Option<u32>,                 // The ID linking this leaf node to a PubSub topic
}

impl QuadTree {
    /// Create the root node of the QuadTree
    pub fn new(bounds: Rect, depth: u8, max_depth: u8) -> Self {
        Self {
            bounds,
            depth,
            max_depth,
            shard_id: Some(0), // The root starts as Shard 0
            children: None,
        }
    }

    /// Split this node into 4 smaller, evenly sized children.
    pub fn split(&mut self) {
        if self.depth >= self.max_depth || self.children.is_some() {
            return; // Can't split if already split or at max depth
        }

        let half_w = self.bounds.width() / 2.0;
        let half_h = self.bounds.height() / 2.0;
        let center = self.bounds.center();

        // Calculate the bounds for the 4 quadrants
        let nw_bounds = Rect::from_center_size(
            Vec2::new(center.x - half_w / 2.0, center.y + half_h / 2.0),
            Vec2::new(half_w, half_h),
        );
        let ne_bounds = Rect::from_center_size(
            Vec2::new(center.x + half_w / 2.0, center.y + half_h / 2.0),
            Vec2::new(half_w, half_h),
        );
        let sw_bounds = Rect::from_center_size(
            Vec2::new(center.x - half_w / 2.0, center.y - half_h / 2.0),
            Vec2::new(half_w, half_h),
        );
        let se_bounds = Rect::from_center_size(
            Vec2::new(center.x + half_w / 2.0, center.y - half_h / 2.0),
            Vec2::new(half_w, half_h),
        );

        let next_depth = self.depth + 1;

        // Instantiate the children
        self.children = Some(Box::new([
            QuadTree::new(nw_bounds, next_depth, self.max_depth),
            QuadTree::new(ne_bounds, next_depth, self.max_depth),
            QuadTree::new(sw_bounds, next_depth, self.max_depth),
            QuadTree::new(se_bounds, next_depth, self.max_depth),
        ]));
        // Note: The parent node KEEPS its shard_id. This makes merging back later very easy!
    }

    /// Recursively define leaf shards in sequence (used for initial setup)
    pub fn assign_shards(&mut self, next_id: &mut u32) {
        if let Some(children) = &mut self.children {
            for child in children.iter_mut() {
                child.assign_shards(next_id);
            }
        } else {
            self.shard_id = Some(*next_id);
            *next_id += 1;
        }
    }

    /// Finds a specific leaf node by its ID and executes a `split()` on it.
    /// It assigns new shard IDs to the 4 children and returns them.
    pub fn split_leaf(&mut self, target_shard_id: u32, next_id: &mut u32) -> Option<[u32; 4]> {
        if let Some(children) = &mut self.children {
            // Keep searching down the tree
            for child in children.iter_mut() {
                if let Some(new_ids) = child.split_leaf(target_shard_id, next_id) {
                    return Some(new_ids);
                }
            }
            None
        } else if self.shard_id == Some(target_shard_id) {
            // Found the target leaf! Execute split.
            self.split();
            
            // Assign sequential IDs to the 4 new children
            if let Some(children) = &mut self.children {
                let mut ids = [0u32; 4];
                for (i, child) in children.iter_mut().enumerate() {
                    child.shard_id = Some(*next_id);
                    ids[i] = *next_id;
                    *next_id += 1;
                }
                Some(ids)
            } else {
                None
            }
        } else {
            None
        }
    }

    /// Return the shard_id of the deepest leaf containing `pos`.
    pub fn shard_for(&self, pos: Vec2) -> Option<u32> {
        if !self.bounds.contains(pos) {
            return None; // Point is outside our bounds
        }

        // If we have children, recursively check which child contains the point
        if let Some(children) = &self.children {
            for child in children.iter() {
                if let Some(id) = child.shard_for(pos) {
                    return Some(id);
                }
            }
        } else {
            // We are a leaf node containing the point, return our ID!
            return self.shard_id;
        }

        None
    }

    /// Return a list of all distinct shard_ids that overlap with a margin box around `pos`.
    /// This calculates the "Ghost zones" a player should subscribe to.
    pub fn shards_near(&self, pos: Vec2, margin: f32) -> Vec<u32> {
        let mut result = Vec::new();
        self.shards_near_impl(pos, margin, &mut result);
        result.sort_unstable();
        result.dedup(); // Remove duplicates
        result
    }

    fn shards_near_impl(&self, pos: Vec2, margin: f32, result: &mut Vec<u32>) {
        // Create a bounding box representing the player's view radius
        let margin_rect = Rect::from_center_size(pos, Vec2::new(margin * 2.0, margin * 2.0));

        if !rects_overlap(self.bounds, margin_rect) {
            return; // Box does not overlap this quadrant at all
        }

        if let Some(children) = &self.children {
            for child in children.iter() {
                child.shards_near_impl(pos, margin, result);
            }
        } else if let Some(id) = self.shard_id {
            // Box overlaps this leaf node! Add it to the list.
            result.push(id);
        }
    }

    /// Analyzes the tree to see if 4 sibling leaves are empty enough to merge back into their parent.
    /// Returns `(parent_shard, [child_1, child_2, child_3, child_4])` if merged.
    pub fn try_merge(&mut self, pop_map: &std::collections::HashMap<u32, usize>, max_pop: usize) -> Option<(u32, [u32; 4])> {
        if let Some(children) = &mut self.children {
            // Try to recursively merge from the bottom of the tree up
            for child in children.iter_mut() {
                if let Some(res) = child.try_merge(pop_map, max_pop) {
                    return Some(res);
                }
            }

            if let Some(parent_id) = self.shard_id {
                // To merge, all 4 children MUST be leaves (no grandchildren)
                let all_leaves = children.iter().all(|c| c.children.is_none());
                if all_leaves {
                    let mut total_pop = 0;
                    let mut child_ids = [0u32; 4];
                    
                    // Sum up the population of the 4 leaves
                    for (i, child) in children.iter().enumerate() {
                        let cid = child.shard_id.unwrap();
                        total_pop += pop_map.get(&cid).copied().unwrap_or(0);
                        child_ids[i] = cid;
                    }

                    // If they are under the threshold, execute the merge!
                    if total_pop <= max_pop {
                        self.children = None; // Dropping the Box deletes the children
                        return Some((parent_id, child_ids));
                    }
                }
            }
        }
        None
    }

    /// Used for catastrophic crash recovery. If a child node crashed, delete the children
    /// and restore the parent node.
    pub fn force_collapse_if_contains(&mut self, crashed_shards: &[u32]) -> bool {
        if let Some(children) = &mut self.children {
            let mut collapse = false;
            for child in children.iter_mut() {
                if child.force_collapse_if_contains(crashed_shards) {
                    collapse = true;
                }
                if let Some(id) = child.shard_id {
                    if crashed_shards.contains(&id) {
                        collapse = true;
                    }
                }
            }

            if collapse {
                self.children = None; // BOOM! Node collapsed.
                return true;
            }
        }
        false
    }

    /// Search the tree to find the parent ID of a specific target child shard.
    pub fn find_parent_of(&self, target_shard: u32) -> Option<u32> {
        if let Some(children) = &self.children {
            for child in children.iter() {
                if let Some(id) = child.shard_id {
                    if id == target_shard {
                        return self.shard_id;
                    }
                }
                if let Some(parent) = child.find_parent_of(target_shard) {
                    return Some(parent);
                }
            }
        }
        None
    }
}

// Simple AABB overlap check
fn rects_overlap(r1: Rect, r2: Rect) -> bool {
    r1.min.x <= r2.max.x && r1.max.x >= r2.min.x && r1.min.y <= r2.max.y && r1.max.y >= r2.min.y
}

// ==========================================
// 3. SPATIAL SERVICE (THE ENGINE)
// ==========================================

/// Holds the active QuadTree and tracks the state of every player in the game.
pub struct SpatialService {
    pub quadtree: QuadTree,
    pub margin: f32, // The radius of a player's view distance
    
    // Tracks the physical location of a player (where their inputs go)
    pub client_primary_shard: std::collections::HashMap<u32, u32>,
    
    // Tracks the ghost zones a player is watching (where they receive broadcasts from)
    pub client_subscribed_shards: std::collections::HashMap<u32, Vec<u32>>,
    
    pub next_shard_id: u32,
    
    // Locks to prevent issuing multiple overlapping commands for the same shards
    pub pending_splits: std::collections::HashSet<u32>,
    pub pending_merges: std::collections::HashSet<u32>, 
}

impl SpatialService {
    // Arbitrary low values so we can easily test scaling logic in dev
    pub const MAX_POPULATION: usize = 2; 
    pub const MIN_POPULATION: usize = 1; 

    pub fn new(quadtree: QuadTree, margin: f32, next_shard_id: u32) -> Self {
        Self {
            quadtree,
            margin,
            client_primary_shard: std::collections::HashMap::new(),
            client_subscribed_shards: std::collections::HashMap::new(),
            next_shard_id,
            pending_splits: std::collections::HashSet::new(),
            pending_merges: std::collections::HashSet::new(),
        }
    }

    /// Mass-rescues stranded players after a server crashes.
    pub fn handle_server_crash(&mut self, crashed_shards: &[u32]) -> Vec<SpatialAction> {
        let mut actions = Vec::new();

        // Step 1: Forcefully delete the crashed shards from the tree
        self.quadtree.force_collapse_if_contains(crashed_shards);

        // Step 2: Iterate over every player. If they were in the crashed shard,
        // find the parent shard and issue an emergency AuthorityChange to move them there.
        for (client_id, primary) in self.client_primary_shard.iter_mut() {
            if crashed_shards.contains(primary) {
                let mut new_shard = 0; // Fallback to root
                if let Some(parent) = self.quadtree.find_parent_of(*primary) {
                    new_shard = parent;
                }

                actions.push(SpatialAction::AuthorityChange {
                    client_id: *client_id,
                    old_shard: *primary,
                    new_shard,
                });
                *primary = new_shard; // Update tracking immediately
            }
        }

        // Release any locks so the parent shard can split again if it gets too full
        for s in crashed_shards {
            self.pending_splits.remove(s);
            self.pending_merges.remove(s);
        }

        actions
    }

    /// The core loop execution: Updates tracking and yields Actions based on player movement.
    pub fn handle_position_update(
        &mut self,
        update: &PositionUpdate,
        pending_ready: &std::collections::HashMap<u32, u32>,
    ) -> Vec<SpatialAction> {
        let mut actions = Vec::new();
        let pos = Vec2::new(update.x, update.y);

        // 1. Where is the player standing?
        let mut new_shard_opt = self.quadtree.shard_for(pos);
        
        // INTERCEPT: If the tree says the player is in Shard X, but Shard X hasn't finished booting yet,
        // we map Shard X back to its parent. The player stays in the parent until the boot is complete.
        if let Some(s) = new_shard_opt {
            if let Some(&parent) = pending_ready.get(&s) {
                new_shard_opt = Some(parent);
            }
        }
        
        // 2. Did the player cross a border?
        if let Some(new_primary) = new_shard_opt {
            let current_primary = self.client_primary_shard.get(&update.client_id).copied();

            if current_primary != Some(new_primary) {
                // Emit an AuthorityChange so the client switches servers
                let old = current_primary.unwrap_or(0);
                actions.push(SpatialAction::AuthorityChange {
                    client_id: update.client_id,
                    old_shard: old,
                    new_shard: new_primary,
                });
                self.client_primary_shard.insert(update.client_id, new_primary);
            }
        }

        // 3. Check for nearby Ghost zones
        let mut near = self.quadtree.shards_near(pos, self.margin);
        
        // INTERCEPT: Map any unready nearby shards back to their parent
        for s in near.iter_mut() {
            if let Some(&parent) = pending_ready.get(s) {
                *s = parent;
            }
        }
        
        // Ensure primary is always in the 'near' list
        if let Some(primary) = new_shard_opt {
            if !near.contains(&primary) {
                near.push(primary);
            }
        }
        near.sort_unstable();
        near.dedup();

        let currently_subscribed = self
            .client_subscribed_shards
            .get(&update.client_id)
            .cloned()
            .unwrap_or_default();

        // 4. Calculate Subscriptions / Unsubscriptions
        // If a nearby shard is not in our current subscriptions, Subscribe!
        for &shard in &near {
            if !currently_subscribed.contains(&shard) {
                actions.push(SpatialAction::Subscribe {
                    client_id: update.client_id,
                    topic: string_to_topic(&format!("shard:{}", shard)),
                });
            }
        }

        // If a current subscription is no longer nearby, Unsubscribe!
        for &shard in &currently_subscribed {
            if !near.contains(&shard) {
                actions.push(SpatialAction::Unsubscribe {
                    client_id: update.client_id,
                    topic: string_to_topic(&format!("shard:{}", shard)),
                });
            }
        }

        self.client_subscribed_shards.insert(update.client_id, near.clone());

        // 5. Emit CrossingAlert (Optional UI/Client feature)
        if near.len() > 1 {
            actions.push(SpatialAction::CrossingAlert {
                client_id: update.client_id,
                shards: near,
            });
        }

        // 6. OVERPOPULATION CHECK (ScaleUp)
        if let Some(primary) = new_shard_opt {
            // Only split if we aren't already waiting for this shard to transition
            if !self.pending_splits.contains(&primary) && !self.pending_merges.contains(&primary) {
                let pop = self.client_primary_shard.values().filter(|&&s| s == primary).count();
                if pop > Self::MAX_POPULATION {
                    self.pending_splits.insert(primary); // Lock it
                    
                    // Modify the tree and yield the ScaleUp command
                    if let Some(new_shards_arr) = self.quadtree.split_leaf(primary, &mut self.next_shard_id) {
                        let new_shards = new_shards_arr.to_vec();
                        actions.push(SpatialAction::ScaleUp {
                            parent_shard: primary,
                            new_shards,
                        });
                    }
                }
            }
        }

        actions
    }

    /// Triggered occasionally or on disconnects. Checks if siblings are empty enough to merge.
    pub fn check_merges(&mut self) -> Vec<SpatialAction> {
        let mut actions = Vec::new();
        
        // Count populations
        let mut pop_map = std::collections::HashMap::new();
        for &shard in self.client_primary_shard.values() {
            *pop_map.entry(shard).or_insert(0) += 1;
        }

        // Execute tree traversal. If a merge happens, yield the ScaleDown command.
        if let Some((parent_shard, old_shards_arr)) = self.quadtree.try_merge(&pop_map, Self::MIN_POPULATION) {
            let old_shards = old_shards_arr.to_vec();
            self.pending_merges.insert(parent_shard); // Lock it
            actions.push(SpatialAction::ScaleDown {
                parent_shard,
                old_shards,
            });
        }

        actions
    }
}
